version: "3.9"

services:
  backend:
    image: asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/backend:latest
    container_name: backend
    ports:
      - "3901:5000"
    restart: always

  frontend:
    image: asia-south1-docker.pkg.dev/meanrevcontact/meanrevrepo/frontend:latest
    container_name: frontend
    ports:
      - "3902:80"
    restart: always
    environment:
      - VITE_API_URL=http://35.207.197.6:3901
    depends_on:
      - backend

